[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ereddicatorcli"
version = "0.1.0"
description = "CLI tool to edit and/or delete your Reddit comments, posts, saved items, votes, and hidden posts."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "praw==7.8.1",
    "requests==2.32.3",
    "platformdirs==4.11.7",
]

[project.urls]
Homepage = "https://github.com/michalhorvath/ereddicatorcli"

[project.scripts]
ereddicator = "ereddicatorcli.main:main"

[tool.setuptools.packages.find]
where = ["src"]
